// <auto-generated />
using System;
using LTSBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LTSBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LTSBackend.Models.Audit.AuditLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordID")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("LogID");

                    b.HasIndex("Timestamp")
                        .IsDescending();

                    b.HasIndex("UserID");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("LTSBackend.Models.Cases.Case", b =>
                {
                    b.Property<long>("CaseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CaseID"));

                    b.Property<string>("CaseDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CaseTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<decimal>("ClaimedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ClosureDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CourtID")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentLegalOfficerID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpectedDisposalDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("FilingDate")
                        .HasColumnType("date");

                    b.Property<string>("FinancialImplication")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("FirmID")
                        .HasColumnType("int");

                    b.Property<DateTime>("InstitutionDate")
                        .HasColumnType("date");

                    b.Property<string>("InternalReferenceNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextHearingDate")
                        .HasColumnType("date");

                    b.Property<decimal>("PotentialLiability")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("date");

                    b.Property<int>("ResponsibleDepartmentID")
                        .HasColumnType("int");

                    b.Property<int>("StageID")
                        .HasColumnType("int");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.Property<string>("SubjectMatter")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpcomingDeadline")
                        .HasColumnType("date");

                    b.HasKey("CaseID");

                    b.HasIndex("CaseNumber");

                    b.HasIndex("CategoryID");

                    b.HasIndex("CourtID");

                    b.HasIndex("CurrentLegalOfficerID");

                    b.HasIndex("FirmID");

                    b.HasIndex("InternalReferenceNo")
                        .IsUnique();

                    b.HasIndex("ResponsibleDepartmentID");

                    b.HasIndex("StageID");

                    b.HasIndex("StatusID");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("LTSBackend.Models.Cases.CaseAssignment", b =>
                {
                    b.Property<long>("AssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AssignmentID"));

                    b.Property<int>("AssignedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignmentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long>("CaseID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LeadCounsel")
                        .HasColumnType("bit")
                        .HasColumnName("IsLeadCounsel");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("AssignmentID");

                    b.HasIndex("UserID");

                    b.HasIndex("CaseID", "EndDate");

                    b.ToTable("CaseAssignments");
                });

            modelBuilder.Entity("LTSBackend.Models.Cases.CaseMilestone", b =>
                {
                    b.Property<long>("MilestoneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MilestoneID"));

                    b.Property<long>("CaseID")
                        .HasColumnType("bigint");

                    b.Property<int>("CompletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Milestone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("MilestoneDate")
                        .HasColumnType("date");

                    b.HasKey("MilestoneID");

                    b.HasIndex("CaseID");

                    b.ToTable("CaseMilestones");
                });

            modelBuilder.Entity("LTSBackend.Models.Cases.CaseNote", b =>
                {
                    b.Property<long>("NoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NoteID"));

                    b.Property<long>("CaseID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoteType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("NoteID");

                    b.HasIndex("CaseID");

                    b.HasIndex("UserID");

                    b.ToTable("CaseNotes");
                });

            modelBuilder.Entity("LTSBackend.Models.Cases.CaseParty", b =>
                {
                    b.Property<long>("PartyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PartyID"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CNIC")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("CaseID")
                        .HasColumnType("bigint");

                    b.Property<string>("ContactNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LawyerName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NTN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Organization")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PartyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PartyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PartyID");

                    b.HasIndex("CaseID");

                    b.ToTable("CaseParties");
                });

            modelBuilder.Entity("LTSBackend.Models.Cases.CaseStatusHistory", b =>
                {
                    b.Property<long>("HistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("HistoryID"));

                    b.Property<long>("CaseID")
                        .HasColumnType("bigint");

                    b.Property<int>("ChangedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NewStatusID")
                        .HasColumnType("int");

                    b.Property<int?>("OldStatusID")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("HistoryID");

                    b.HasIndex("CaseID");

                    b.ToTable("CaseStatusHistory");
                });

            modelBuilder.Entity("LTSBackend.Models.Cases.Deadline", b =>
                {
                    b.Property<long>("DeadlineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DeadlineID"));

                    b.Property<long>("CaseID")
                        .HasColumnType("bigint");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeadlineType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ReminderDays")
                        .HasColumnType("int");

                    b.HasKey("DeadlineID");

                    b.HasIndex("DueDate");

                    b.HasIndex("CaseID", "Completed");

                    b.ToTable("Deadlines");
                });

            modelBuilder.Entity("LTSBackend.Models.Cases.Document", b =>
                {
                    b.Property<long>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DocumentID"));

                    b.Property<long>("CaseID")
                        .HasColumnType("bigint");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DocumentTypeID")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("bit");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("DocumentID");

                    b.HasIndex("CaseID");

                    b.HasIndex("DocumentTypeID");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("LTSBackend.Models.Cases.DocumentPermission", b =>
                {
                    b.Property<long>("PermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PermissionID"));

                    b.Property<bool>("CanDownload")
                        .HasColumnType("bit");

                    b.Property<bool>("CanUpload")
                        .HasColumnType("bit");

                    b.Property<bool>("CanView")
                        .HasColumnType("bit");

                    b.Property<long>("DocumentID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GrantedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RoleID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("PermissionID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID");

                    b.HasIndex("DocumentID", "RoleID");

                    b.HasIndex("DocumentID", "UserID");

                    b.ToTable("DocumentPermissions");
                });

            modelBuilder.Entity("LTSBackend.Models.Cases.Hearing", b =>
                {
                    b.Property<long>("HearingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("HearingID"));

                    b.Property<long>("CaseID")
                        .HasColumnType("bigint");

                    b.Property<int>("CourtID")
                        .HasColumnType("int");

                    b.Property<string>("CourtRoom")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HearingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("JudgeName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("NextHearingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Outcome")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Purpose")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("HearingID");

                    b.HasIndex("CaseID");

                    b.HasIndex("CourtID");

                    b.HasIndex("HearingDate");

                    b.ToTable("Hearings");
                });

            modelBuilder.Entity("LTSBackend.Models.Cases.HearingAttendance", b =>
                {
                    b.Property<long>("AttendanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AttendanceID"));

                    b.Property<DateTime?>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("AttendanceRole")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("HearingID")
                        .HasColumnType("bigint");

                    b.Property<bool>("Present")
                        .HasColumnType("bit");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("AttendanceID");

                    b.HasIndex("UserID");

                    b.HasIndex("HearingID", "UserID")
                        .IsUnique();

                    b.ToTable("HearingAttendance");
                });

            modelBuilder.Entity("LTSBackend.Models.Cases.Notification", b =>
                {
                    b.Property<long>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NotificationID"));

                    b.Property<long?>("CaseID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSent")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotificationTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("NotificationID");

                    b.HasIndex("CaseID");

                    b.HasIndex("NotificationTypeID");

                    b.HasIndex("UserID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("LTSBackend.Models.Masters.CaseCategory", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryID");

                    b.ToTable("CaseCategories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Civil",
                            Description = "Civil matters and disputes"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Criminal",
                            Description = "Criminal cases"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Constitutional",
                            Description = "Constitutional matters"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Corporate",
                            Description = "Corporate and commercial disputes"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Labour",
                            Description = "Labour and employment disputes"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Administrative",
                            Description = "Administrative law matters"
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Banking",
                            Description = "Banking and financial disputes"
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryName = "Tax",
                            Description = "Tax-related matters"
                        });
                });

            modelBuilder.Entity("LTSBackend.Models.Masters.CaseStage", b =>
                {
                    b.Property<int>("StageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StageID"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("StageID");

                    b.ToTable("CaseStages");

                    b.HasData(
                        new
                        {
                            StageID = 1,
                            Description = "Initial case filing stage",
                            StageName = "Filing"
                        },
                        new
                        {
                            StageID = 2,
                            Description = "Case admission by court",
                            StageName = "Admission"
                        },
                        new
                        {
                            StageID = 3,
                            Description = "Evidence submission stage",
                            StageName = "Evidence"
                        },
                        new
                        {
                            StageID = 4,
                            Description = "Oral arguments before court",
                            StageName = "Arguments"
                        },
                        new
                        {
                            StageID = 5,
                            Description = "Judgment delivery",
                            StageName = "Judgment"
                        },
                        new
                        {
                            StageID = 6,
                            Description = "Appeal proceedings",
                            StageName = "Appeal"
                        });
                });

            modelBuilder.Entity("LTSBackend.Models.Masters.CaseStatus", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusID"));

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("int");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StatusID");

                    b.ToTable("CaseStatus");

                    b.HasData(
                        new
                        {
                            StatusID = 1,
                            ColorCode = "#0066CC",
                            IsActive = true,
                            IsClosed = false,
                            SequenceNo = 1,
                            StatusName = "New"
                        },
                        new
                        {
                            StatusID = 2,
                            ColorCode = "#FF9900",
                            IsActive = true,
                            IsClosed = false,
                            SequenceNo = 2,
                            StatusName = "Pending"
                        },
                        new
                        {
                            StatusID = 3,
                            ColorCode = "#00CC66",
                            IsActive = true,
                            IsClosed = false,
                            SequenceNo = 3,
                            StatusName = "Active"
                        },
                        new
                        {
                            StatusID = 4,
                            ColorCode = "#FF6600",
                            IsActive = true,
                            IsClosed = false,
                            SequenceNo = 4,
                            StatusName = "Hearing Scheduled"
                        },
                        new
                        {
                            StatusID = 5,
                            ColorCode = "#9900CC",
                            IsActive = true,
                            IsClosed = false,
                            SequenceNo = 5,
                            StatusName = "Judgment Reserved"
                        },
                        new
                        {
                            StatusID = 6,
                            ColorCode = "#666666",
                            IsActive = true,
                            IsClosed = true,
                            SequenceNo = 6,
                            StatusName = "Closed"
                        },
                        new
                        {
                            StatusID = 7,
                            ColorCode = "#999999",
                            IsActive = true,
                            IsClosed = true,
                            SequenceNo = 7,
                            StatusName = "Archived"
                        });
                });

            modelBuilder.Entity("LTSBackend.Models.Masters.Court", b =>
                {
                    b.Property<int>("CourtID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourtID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CourtName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CourtType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("CourtID");

                    b.ToTable("Courts");

                    b.HasData(
                        new
                        {
                            CourtID = 1,
                            Address = "Constitution Avenue, Islamabad",
                            CourtName = "Supreme Court of Pakistan",
                            CourtType = "Federal",
                            Jurisdiction = "National"
                        },
                        new
                        {
                            CourtID = 2,
                            Address = "H-8/4, Islamabad",
                            CourtName = "Islamabad High Court",
                            CourtType = "High Court",
                            Jurisdiction = "Islamabad Capital Territory"
                        },
                        new
                        {
                            CourtID = 3,
                            Address = "The Mall, Lahore",
                            CourtName = "Lahore High Court",
                            CourtType = "High Court",
                            Jurisdiction = "Punjab"
                        },
                        new
                        {
                            CourtID = 4,
                            Address = "Constitution Avenue, Karachi",
                            CourtName = "Sindh High Court",
                            CourtType = "High Court",
                            Jurisdiction = "Sindh"
                        },
                        new
                        {
                            CourtID = 5,
                            Address = "Peshawar",
                            CourtName = "Peshawar High Court",
                            CourtType = "High Court",
                            Jurisdiction = "Khyber Pakhtunkhwa"
                        },
                        new
                        {
                            CourtID = 6,
                            Address = "Quetta",
                            CourtName = "Quetta High Court",
                            CourtType = "High Court",
                            Jurisdiction = "Balochistan"
                        },
                        new
                        {
                            CourtID = 7,
                            Address = "Thokar Niaz Baig, Lahore",
                            CourtName = "District Court Lahore",
                            CourtType = "District Court",
                            Jurisdiction = "Lahore District"
                        },
                        new
                        {
                            CourtID = 8,
                            Address = "Karachi",
                            CourtName = "District Court Karachi",
                            CourtType = "District Court",
                            Jurisdiction = "Karachi District"
                        });
                });

            modelBuilder.Entity("LTSBackend.Models.Masters.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentID = 1,
                            DepartmentCode = "FIN",
                            DepartmentName = "Finance Department",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentID = 2,
                            DepartmentCode = "REV",
                            DepartmentName = "Revenue Department",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentID = 3,
                            DepartmentCode = "LAW",
                            DepartmentName = "Law Department",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentID = 4,
                            DepartmentCode = "DEF",
                            DepartmentName = "Defense Department",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentID = 5,
                            DepartmentCode = "INT",
                            DepartmentName = "Interior Department",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("LTSBackend.Models.Masters.DocumentType", b =>
                {
                    b.Property<int>("DocumentTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentTypeID"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("DocumentTypeID");

                    b.ToTable("DocumentTypes");

                    b.HasData(
                        new
                        {
                            DocumentTypeID = 1,
                            Description = "Main petition/plaint document",
                            TypeName = "Petition"
                        },
                        new
                        {
                            DocumentTypeID = 2,
                            Description = "Sworn affidavit",
                            TypeName = "Affidavit"
                        },
                        new
                        {
                            DocumentTypeID = 3,
                            Description = "Order issued by court",
                            TypeName = "Court Order"
                        },
                        new
                        {
                            DocumentTypeID = 4,
                            Description = "Supporting evidence documents",
                            TypeName = "Evidence"
                        },
                        new
                        {
                            DocumentTypeID = 5,
                            Description = "Reply to petition/arguments",
                            TypeName = "Reply"
                        },
                        new
                        {
                            DocumentTypeID = 6,
                            Description = "Final judgment document",
                            TypeName = "Judgment"
                        },
                        new
                        {
                            DocumentTypeID = 7,
                            Description = "Legal notices",
                            TypeName = "Notice"
                        },
                        new
                        {
                            DocumentTypeID = 8,
                            Description = "Appeal documents",
                            TypeName = "Appeal"
                        });
                });

            modelBuilder.Entity("LTSBackend.Models.Security.Firm", b =>
                {
                    b.Property<int>("FirmID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FirmID"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("BlockedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BlockedBy")
                        .HasColumnType("int");

                    b.Property<string>("BlockedReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CustomDomain")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("FirmCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FirmName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MigrationCompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MigrationNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("MigrationRequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MigrationRequestedBy")
                        .HasColumnType("int");

                    b.Property<string>("MigrationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("None");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("FirmID");

                    b.HasIndex("FirmCode")
                        .IsUnique();

                    b.ToTable("Firms");

                    b.HasData(
                        new
                        {
                            FirmID = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 0,
                            FirmCode = "DEMO",
                            FirmName = "Demo Law Firm",
                            IsBlocked = false,
                            IsDeleted = false,
                            MigrationNotes = "Development/Testing Firm",
                            MigrationStatus = "None"
                        },
                        new
                        {
                            FirmID = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 0,
                            FirmCode = "TEST",
                            FirmName = "Test Law Firm",
                            IsBlocked = false,
                            IsDeleted = false,
                            MigrationNotes = "QA Testing Firm",
                            MigrationStatus = "None"
                        });
                });

            modelBuilder.Entity("LTSBackend.Models.Security.LoginHistory", b =>
                {
                    b.Property<int>("LoginID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoginID"));

                    b.Property<string>("IPAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsLoggedOut")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LogoutTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("LoginID");

                    b.HasIndex("UserID", "LoginTime")
                        .IsDescending(false, true);

                    b.ToTable("LoginHistories");
                });

            modelBuilder.Entity("LTSBackend.Models.Security.NotificationType", b =>
                {
                    b.Property<int>("NotificationTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationTypeID"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInApp")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSMS")
                        .HasColumnType("bit");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("NotificationTypeID");

                    b.HasIndex("TypeName")
                        .IsUnique();

                    b.ToTable("NotificationTypes");

                    b.HasData(
                        new
                        {
                            NotificationTypeID = 1,
                            Description = "Reminder for approaching case deadline",
                            IsActive = true,
                            IsEmail = true,
                            IsInApp = true,
                            IsSMS = false,
                            TypeName = "DeadlineAlert"
                        },
                        new
                        {
                            NotificationTypeID = 2,
                            Description = "Reminder for upcoming court hearing",
                            IsActive = true,
                            IsEmail = true,
                            IsInApp = true,
                            IsSMS = false,
                            TypeName = "HearingReminder"
                        },
                        new
                        {
                            NotificationTypeID = 3,
                            Description = "Notification when case is assigned",
                            IsActive = true,
                            IsEmail = true,
                            IsInApp = true,
                            IsSMS = false,
                            TypeName = "CaseAssignment"
                        },
                        new
                        {
                            NotificationTypeID = 4,
                            Description = "Notification when document uploaded to case",
                            IsActive = true,
                            IsEmail = false,
                            IsInApp = true,
                            IsSMS = false,
                            TypeName = "DocumentUploaded"
                        },
                        new
                        {
                            NotificationTypeID = 5,
                            Description = "Notification when case status changes",
                            IsActive = true,
                            IsEmail = true,
                            IsInApp = true,
                            IsSMS = false,
                            TypeName = "CaseStatusChanged"
                        });
                });

            modelBuilder.Entity("LTSBackend.Models.Security.Permission", b =>
                {
                    b.Property<int>("PermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionID"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PermissionID");

                    b.HasIndex("PermissionName")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            PermissionID = 101,
                            Description = "Create, block, remove firms",
                            PermissionName = "ManageFirms"
                        },
                        new
                        {
                            PermissionID = 102,
                            Description = "View system-wide audit logs",
                            PermissionName = "ViewSystemAuditLogs"
                        },
                        new
                        {
                            PermissionID = 103,
                            Description = "Manage firm data migration",
                            PermissionName = "ManageDataMigration"
                        },
                        new
                        {
                            PermissionID = 104,
                            Description = "Manage all system users",
                            PermissionName = "ManageSystemUsers"
                        },
                        new
                        {
                            PermissionID = 201,
                            Description = "Create and manage firm users",
                            PermissionName = "ManageFirmUsers"
                        },
                        new
                        {
                            PermissionID = 202,
                            Description = "View all cases in firm",
                            PermissionName = "ViewFirmCaseDirectory"
                        },
                        new
                        {
                            PermissionID = 203,
                            Description = "Assign lawyers to cases",
                            PermissionName = "AssignLawyersToCases"
                        },
                        new
                        {
                            PermissionID = 204,
                            Description = "Manage firm settings and billing",
                            PermissionName = "ManageFirmSettings"
                        },
                        new
                        {
                            PermissionID = 205,
                            Description = "Delete cases",
                            PermissionName = "DeleteCases"
                        },
                        new
                        {
                            PermissionID = 402,
                            Description = "Upload documents",
                            PermissionName = "UploadDocuments"
                        },
                        new
                        {
                            PermissionID = 301,
                            Description = "View firm cases",
                            PermissionName = "ViewFirmCases"
                        },
                        new
                        {
                            PermissionID = 302,
                            Description = "Create new cases",
                            PermissionName = "CreateCases"
                        },
                        new
                        {
                            PermissionID = 303,
                            Description = "Update case information",
                            PermissionName = "UpdateCases"
                        },
                        new
                        {
                            PermissionID = 304,
                            Description = "Assign cases to lawyers",
                            PermissionName = "AssignCases"
                        },
                        new
                        {
                            PermissionID = 305,
                            Description = "View all case documents",
                            PermissionName = "ViewAllDocuments"
                        },
                        new
                        {
                            PermissionID = 306,
                            Description = "Download documents",
                            PermissionName = "DownloadDocuments"
                        },
                        new
                        {
                            PermissionID = 307,
                            Description = "Approve critical filings",
                            PermissionName = "ApproveFilings"
                        },
                        new
                        {
                            PermissionID = 308,
                            Description = "View firm analytics and reports",
                            PermissionName = "ViewFirmAnalytics"
                        },
                        new
                        {
                            PermissionID = 401,
                            Description = "View assigned cases only",
                            PermissionName = "ViewAssignedCases"
                        },
                        new
                        {
                            PermissionID = 403,
                            Description = "Download assigned case documents",
                            PermissionName = "DownloadAssignedDocuments"
                        },
                        new
                        {
                            PermissionID = 404,
                            Description = "Add notes to cases",
                            PermissionName = "AddCaseNotes"
                        },
                        new
                        {
                            PermissionID = 405,
                            Description = "Track case deadlines",
                            PermissionName = "TrackDeadlines"
                        },
                        new
                        {
                            PermissionID = 406,
                            Description = "Log billable hours",
                            PermissionName = "LogBillableHours"
                        },
                        new
                        {
                            PermissionID = 501,
                            Description = "Enter case data",
                            PermissionName = "EnterCaseData"
                        },
                        new
                        {
                            PermissionID = 502,
                            Description = "Upload case documents",
                            PermissionName = "UploadCaseDocuments"
                        },
                        new
                        {
                            PermissionID = 503,
                            Description = "View documents if permitted",
                            PermissionName = "ViewDocumentsIfPermitted"
                        },
                        new
                        {
                            PermissionID = 504,
                            Description = "Download documents if permitted",
                            PermissionName = "DownloadDocumentsIfPermitted"
                        },
                        new
                        {
                            PermissionID = 505,
                            Description = "Maintain case records",
                            PermissionName = "MaintainCaseRecords"
                        },
                        new
                        {
                            PermissionID = 601,
                            Description = "View documents (read-only)",
                            PermissionName = "ViewDocumentsReadOnly"
                        },
                        new
                        {
                            PermissionID = 602,
                            Description = "Draft legal documents",
                            PermissionName = "DraftDocuments"
                        },
                        new
                        {
                            PermissionID = 603,
                            Description = "Perform legal research",
                            PermissionName = "PerformResearch"
                        });
                });

            modelBuilder.Entity("LTSBackend.Models.Security.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefreshTokenID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("RefreshTokenID");

                    b.HasIndex("UserID");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("LTSBackend.Models.Security.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleID");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            Description = "System-wide management and data custody",
                            IsActive = true,
                            IsSystemRole = true,
                            RoleName = "SuperAdmin"
                        },
                        new
                        {
                            RoleID = 2,
                            Description = "Workspace owner - manages specific law firm",
                            IsActive = true,
                            IsSystemRole = false,
                            RoleName = "FirmAdmin"
                        },
                        new
                        {
                            RoleID = 3,
                            Description = "Senior lawyer - supervises case teams",
                            IsActive = true,
                            IsSystemRole = false,
                            RoleName = "Partner"
                        },
                        new
                        {
                            RoleID = 4,
                            Description = "Day-to-day legal work",
                            IsActive = true,
                            IsSystemRole = false,
                            RoleName = "AssociateLawyer"
                        },
                        new
                        {
                            RoleID = 5,
                            Description = "Legal clerk / Data entry operator",
                            IsActive = true,
                            IsSystemRole = false,
                            RoleName = "Moharrir"
                        },
                        new
                        {
                            RoleID = 6,
                            Description = "Temporary staff / Junior assistant",
                            IsActive = true,
                            IsSystemRole = false,
                            RoleName = "InternParalegal"
                        });
                });

            modelBuilder.Entity("LTSBackend.Models.Security.RolePermission", b =>
                {
                    b.Property<int>("RolePermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolePermissionID"));

                    b.Property<int>("PermissionID")
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.HasKey("RolePermissionID");

                    b.HasIndex("PermissionID");

                    b.HasIndex("RoleID", "PermissionID")
                        .IsUnique();

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RolePermissionID = 1,
                            PermissionID = 101,
                            RoleID = 1
                        },
                        new
                        {
                            RolePermissionID = 2,
                            PermissionID = 102,
                            RoleID = 1
                        },
                        new
                        {
                            RolePermissionID = 3,
                            PermissionID = 103,
                            RoleID = 1
                        },
                        new
                        {
                            RolePermissionID = 4,
                            PermissionID = 104,
                            RoleID = 1
                        },
                        new
                        {
                            RolePermissionID = 5,
                            PermissionID = 201,
                            RoleID = 2
                        },
                        new
                        {
                            RolePermissionID = 6,
                            PermissionID = 202,
                            RoleID = 2
                        },
                        new
                        {
                            RolePermissionID = 7,
                            PermissionID = 203,
                            RoleID = 2
                        },
                        new
                        {
                            RolePermissionID = 8,
                            PermissionID = 204,
                            RoleID = 2
                        },
                        new
                        {
                            RolePermissionID = 9,
                            PermissionID = 205,
                            RoleID = 2
                        },
                        new
                        {
                            RolePermissionID = 10,
                            PermissionID = 301,
                            RoleID = 2
                        },
                        new
                        {
                            RolePermissionID = 11,
                            PermissionID = 302,
                            RoleID = 2
                        },
                        new
                        {
                            RolePermissionID = 12,
                            PermissionID = 303,
                            RoleID = 2
                        },
                        new
                        {
                            RolePermissionID = 13,
                            PermissionID = 305,
                            RoleID = 2
                        },
                        new
                        {
                            RolePermissionID = 14,
                            PermissionID = 306,
                            RoleID = 2
                        },
                        new
                        {
                            RolePermissionID = 15,
                            PermissionID = 402,
                            RoleID = 2
                        },
                        new
                        {
                            RolePermissionID = 16,
                            PermissionID = 308,
                            RoleID = 2
                        },
                        new
                        {
                            RolePermissionID = 17,
                            PermissionID = 202,
                            RoleID = 3
                        },
                        new
                        {
                            RolePermissionID = 18,
                            PermissionID = 203,
                            RoleID = 3
                        },
                        new
                        {
                            RolePermissionID = 19,
                            PermissionID = 304,
                            RoleID = 3
                        },
                        new
                        {
                            RolePermissionID = 20,
                            PermissionID = 205,
                            RoleID = 3
                        },
                        new
                        {
                            RolePermissionID = 21,
                            PermissionID = 301,
                            RoleID = 3
                        },
                        new
                        {
                            RolePermissionID = 22,
                            PermissionID = 302,
                            RoleID = 3
                        },
                        new
                        {
                            RolePermissionID = 23,
                            PermissionID = 303,
                            RoleID = 3
                        },
                        new
                        {
                            RolePermissionID = 24,
                            PermissionID = 305,
                            RoleID = 3
                        },
                        new
                        {
                            RolePermissionID = 25,
                            PermissionID = 306,
                            RoleID = 3
                        },
                        new
                        {
                            RolePermissionID = 26,
                            PermissionID = 402,
                            RoleID = 3
                        },
                        new
                        {
                            RolePermissionID = 27,
                            PermissionID = 307,
                            RoleID = 3
                        },
                        new
                        {
                            RolePermissionID = 28,
                            PermissionID = 308,
                            RoleID = 3
                        },
                        new
                        {
                            RolePermissionID = 29,
                            PermissionID = 401,
                            RoleID = 4
                        },
                        new
                        {
                            RolePermissionID = 30,
                            PermissionID = 402,
                            RoleID = 4
                        },
                        new
                        {
                            RolePermissionID = 31,
                            PermissionID = 403,
                            RoleID = 4
                        },
                        new
                        {
                            RolePermissionID = 32,
                            PermissionID = 404,
                            RoleID = 4
                        },
                        new
                        {
                            RolePermissionID = 33,
                            PermissionID = 405,
                            RoleID = 4
                        },
                        new
                        {
                            RolePermissionID = 34,
                            PermissionID = 406,
                            RoleID = 4
                        },
                        new
                        {
                            RolePermissionID = 35,
                            PermissionID = 501,
                            RoleID = 5
                        },
                        new
                        {
                            RolePermissionID = 36,
                            PermissionID = 502,
                            RoleID = 5
                        },
                        new
                        {
                            RolePermissionID = 37,
                            PermissionID = 505,
                            RoleID = 5
                        },
                        new
                        {
                            RolePermissionID = 38,
                            PermissionID = 601,
                            RoleID = 6
                        },
                        new
                        {
                            RolePermissionID = 39,
                            PermissionID = 602,
                            RoleID = 6
                        },
                        new
                        {
                            RolePermissionID = 40,
                            PermissionID = 603,
                            RoleID = 6
                        });
                });

            modelBuilder.Entity("LTSBackend.Models.Security.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<int?>("FirmID")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PasswordChangedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfileImage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("RoleID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FirmID");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Designation = "System Administrator",
                            Email = "superadmin@lts.pk",
                            EmployeeNo = "",
                            FailedLoginAttempts = 0,
                            FullName = "Super Administrator",
                            IsActive = true,
                            IsDeleted = false,
                            IsExternal = false,
                            PasswordHash = "$2a$11$placeholder_superadmin_hash_replace_in_production"
                        },
                        new
                        {
                            UserID = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Designation = "Firm Administrator",
                            Email = "admin@demolaw.pk",
                            EmployeeNo = "",
                            FailedLoginAttempts = 0,
                            FirmID = 1,
                            FullName = "Firm Administrator",
                            IsActive = true,
                            IsDeleted = false,
                            IsExternal = false,
                            PasswordHash = "$2a$11$placeholder_firmadmin_hash_replace_in_production"
                        },
                        new
                        {
                            UserID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Designation = "Senior Partner",
                            Email = "partner@demolaw.pk",
                            EmployeeNo = "",
                            FailedLoginAttempts = 0,
                            FirmID = 1,
                            FullName = "Muhammad Ashraf (Partner)",
                            IsActive = true,
                            IsDeleted = false,
                            IsExternal = false,
                            PasswordHash = "$2a$11$placeholder_partner_hash_replace_in_production"
                        },
                        new
                        {
                            UserID = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Designation = "Associate Lawyer",
                            Email = "associate@demolaw.pk",
                            EmployeeNo = "",
                            FailedLoginAttempts = 0,
                            FirmID = 1,
                            FullName = "Ayesha Khan (Associate)",
                            IsActive = true,
                            IsDeleted = false,
                            IsExternal = false,
                            PasswordHash = "$2a$11$placeholder_associate_hash_replace_in_production"
                        },
                        new
                        {
                            UserID = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Designation = "Legal Clerk",
                            Email = "moharrir@demolaw.pk",
                            EmployeeNo = "",
                            FailedLoginAttempts = 0,
                            FirmID = 1,
                            FullName = "Hassan Ali (Moharrir)",
                            IsActive = true,
                            IsDeleted = false,
                            IsExternal = false,
                            PasswordHash = "$2a$11$placeholder_moharrir_hash_replace_in_production"
                        },
                        new
                        {
                            UserID = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Designation = "Paralegal Intern",
                            Email = "intern@demolaw.pk",
                            EmployeeNo = "",
                            FailedLoginAttempts = 0,
                            FirmID = 1,
                            FullName = "Amna Saeed (Intern)",
                            IsActive = true,
                            IsDeleted = false,
                            IsExternal = false,
                            PasswordHash = "$2a$11$placeholder_intern_hash_replace_in_production"
                        });
                });

            modelBuilder.Entity("LTSBackend.Models.Security.UserOtp", b =>
                {
                    b.Property<int>("OtpID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OtpID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("Purpose")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("OtpID");

                    b.HasIndex("UserID");

                    b.HasIndex("Email", "OtpCode");

                    b.ToTable("UserOtps");
                });

            modelBuilder.Entity("LTSBackend.Models.Audit.AuditLog", b =>
                {
                    b.HasOne("LTSBackend.Models.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LTSBackend.Models.Cases.Case", b =>
                {
                    b.HasOne("LTSBackend.Models.Masters.CaseCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LTSBackend.Models.Masters.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LTSBackend.Models.Security.User", "LegalOfficer")
                        .WithMany()
                        .HasForeignKey("CurrentLegalOfficerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LTSBackend.Models.Security.Firm", "Firm")
                        .WithMany()
                        .HasForeignKey("FirmID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LTSBackend.Models.Masters.Department", "Department")
                        .WithMany()
                        .HasForeignKey("ResponsibleDepartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LTSBackend.Models.Masters.CaseStage", "Stage")
                        .WithMany()
                        .HasForeignKey("StageID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LTSBackend.Models.Masters.CaseStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Court");

                    b.Navigation("Department");

                    b.Navigation("Firm");

                    b.Navigation("LegalOfficer");

                    b.Navigation("Stage");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("LTSBackend.Models.Cases.CaseAssignment", b =>
                {
                    b.HasOne("LTSBackend.Models.Cases.Case", "Case")
                        .WithMany("CaseAssignments")
                        .HasForeignKey("CaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LTSBackend.Models.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LTSBackend.Models.Cases.CaseMilestone", b =>
                {
                    b.HasOne("LTSBackend.Models.Cases.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("LTSBackend.Models.Cases.CaseNote", b =>
                {
                    b.HasOne("LTSBackend.Models.Cases.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LTSBackend.Models.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LTSBackend.Models.Cases.CaseParty", b =>
                {
                    b.HasOne("LTSBackend.Models.Cases.Case", "Case")
                        .WithMany("CaseParties")
                        .HasForeignKey("CaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("LTSBackend.Models.Cases.CaseStatusHistory", b =>
                {
                    b.HasOne("LTSBackend.Models.Cases.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("LTSBackend.Models.Cases.Deadline", b =>
                {
                    b.HasOne("LTSBackend.Models.Cases.Case", "Case")
                        .WithMany("Deadlines")
                        .HasForeignKey("CaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("LTSBackend.Models.Cases.Document", b =>
                {
                    b.HasOne("LTSBackend.Models.Cases.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LTSBackend.Models.Masters.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("LTSBackend.Models.Cases.DocumentPermission", b =>
                {
                    b.HasOne("LTSBackend.Models.Cases.Document", "Document")
                        .WithMany("DocumentPermissions")
                        .HasForeignKey("DocumentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LTSBackend.Models.Security.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LTSBackend.Models.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Document");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LTSBackend.Models.Cases.Hearing", b =>
                {
                    b.HasOne("LTSBackend.Models.Cases.Case", "Case")
                        .WithMany("Hearings")
                        .HasForeignKey("CaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LTSBackend.Models.Masters.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Court");
                });

            modelBuilder.Entity("LTSBackend.Models.Cases.HearingAttendance", b =>
                {
                    b.HasOne("LTSBackend.Models.Cases.Hearing", "Hearing")
                        .WithMany("HearingAttendances")
                        .HasForeignKey("HearingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LTSBackend.Models.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hearing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LTSBackend.Models.Cases.Notification", b =>
                {
                    b.HasOne("LTSBackend.Models.Cases.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LTSBackend.Models.Security.NotificationType", "NotificationType")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LTSBackend.Models.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("NotificationType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LTSBackend.Models.Security.LoginHistory", b =>
                {
                    b.HasOne("LTSBackend.Models.Security.User", "User")
                        .WithMany("LoginHistories")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LTSBackend.Models.Security.RefreshToken", b =>
                {
                    b.HasOne("LTSBackend.Models.Security.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LTSBackend.Models.Security.RolePermission", b =>
                {
                    b.HasOne("LTSBackend.Models.Security.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LTSBackend.Models.Security.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LTSBackend.Models.Security.User", b =>
                {
                    b.HasOne("LTSBackend.Models.Security.Firm", "Firm")
                        .WithMany("Users")
                        .HasForeignKey("FirmID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LTSBackend.Models.Security.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID");

                    b.Navigation("Firm");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LTSBackend.Models.Security.UserOtp", b =>
                {
                    b.HasOne("LTSBackend.Models.Security.User", "User")
                        .WithMany("UserOtps")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("LTSBackend.Models.Cases.Case", b =>
                {
                    b.Navigation("CaseAssignments");

                    b.Navigation("CaseParties");

                    b.Navigation("Deadlines");

                    b.Navigation("Hearings");
                });

            modelBuilder.Entity("LTSBackend.Models.Cases.Document", b =>
                {
                    b.Navigation("DocumentPermissions");
                });

            modelBuilder.Entity("LTSBackend.Models.Cases.Hearing", b =>
                {
                    b.Navigation("HearingAttendances");
                });

            modelBuilder.Entity("LTSBackend.Models.Security.Firm", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("LTSBackend.Models.Security.NotificationType", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("LTSBackend.Models.Security.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("LTSBackend.Models.Security.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("LTSBackend.Models.Security.User", b =>
                {
                    b.Navigation("LoginHistories");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserOtps");
                });
#pragma warning restore 612, 618
        }
    }
}
